In [1]:
import numpy as np

### 1. Import the numpy library and create the "grades" array as specified above.

In [2]:
grades = np.array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

### 3. Use numpy functions to calculate the mean, median, and standard deviation of the grades.


In [4]:
#mean
mean_1 = np.mean(grades)
mean_1

87.5

In [5]:
#median
med_1 = np.median(grades)
med_1

88.5

In [6]:
#standard deviation
stad_1 = np.std(grades)
stad_1

6.591661399070799

### 4. Use numpy function to find the maximum and minimum of the grades.

In [7]:
#maximum
max_1 = np.max(grades)
max_1

98

In [8]:
#minimum
min_1 = np.min(grades)
min_1

75

### 5. Use numpy function to sort the grades in ascending order.


In [9]:
sort_1 = np.sort(grades)
sort_1

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

### 6. Use numpy function to find the index of the highest grade in the array.

In [17]:
highest_grade_index = np.argmax(grades)
print(highest_grade_index)

7


### 7. Use numpy function to count the number of students who scored above 90

In [22]:
count_90_above = np.count_nonzero(grades >= 90)
count_90_above

4

### 8. Use numpy function to calculate the percentage of students who scored above 90

In [29]:
above_90 = np.count_nonzero(grades > 90)  
  
per_above_90 = (above_90 / len(grades)) * 100  

print(f"{per_above_90} %")

30.0 %


### 9. Use numpy function to calculate the percentage of students who scored below 75

In [31]:
below_75 = np.count_nonzero(grades <75)

per_blow_75 = (below_75/ len(grades)) * 100

print(f"{per_blow_75} %")

0.0 %


### 10. Use numpy function to extract all the grades above 90 and put them in a new array called "high_performers".

In [39]:
high_performers= grades[grades >90]
high_performers


array([90, 92, 95, 98])

### 11. Create a new array called "passing_grades" that contains all the grades above 75.

In [42]:
pass_grades = grades [grades >75]
pass_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])